export enum State {
    Data = "Data",
    TagOpen = "TagOpen",
    EndTagOpen = "EndTagOpen",
    TagName = "TagName",
    SelfClosingStartTag = "SelfClosingStartTag",
    BeforeAttributeName = "BeforeAttributeName",
    AttributeName = "AttributeName",
    AfterAttributeName = "AfterAttributeName",
    BeforeAttributeValue = "BeforeAttributeValue",
    AttributeValueQuoted = "AttributeValueQuoted",
    AttributeValueExpression = "AttributeValueExpression",
    AfterAttributeValueQuoted = "AfterAttributeValueQuoted",
    AfterAttributeValueExpression = "AfterAttributeValueExpression",
    End = "End",
}
